### PR TITLE
added Books Model

### PR DESCRIPTION
**Pull request by DougVonMoser**

### CODE REVIEW

**Comment by christophercook14** [comment]
Doug, I think we should user an integer for bookscore instead of a string.

**Comment by jmy-kellogg** [comment]
Also, don't forget to change define "user" to define "book" :)

**Comment by DougVonMoser** [comment]
btw, addressing issue #2.

**Comment by christophercook14** [comment]
thumbs up!

**Comment by DougVonMoser** [comment]
closes #2

**Pull request merged**
