### PR TITLE
Set up view

### PR DESCRIPTION
**Pull request by jmy-kellogg**
#27 

Moved all of the examples browser files to .graceShopper_browser_example folder.
Set up bare bones ng-app (BookstackApp) and updated Server/app/views for the basic html.

### CODE REVIEW

**Comment by christophercook14** [comment]
works for me

**Comment by jmy-kellogg** [comment]
I've updated a quick test home state. Everything is working with gulp.

**Comment by christophercook14** [comment]
since this is a million changes but mostly just structural, I'm going to assume it is ok as long as it doesn't cause any errors on your machine when run

**Comment by jmy-kellogg** [comment]
Yeah, much of the changes are simply from moving folders. Could one of check out my branch and make sure it's running fine for you guys before a merge anthing

**Comment by jmy-kellogg** [comment]
I'm going to merge the basic set up before moving on to other front-end areas.

**Pull request merged**
