### PR TITLE
created navbar directive and added to html files

### PR DESCRIPTION
**Pull request by jmy-kellogg**
added a navbar directive in the js/common folder. This is added to the html pages. Currently it's set up so it changes to the correct state. More tabs and states can be added.

### CODE REVIEW

**Comment by jmy-kellogg** [comment]
This references issue #30

**Comment by christophercook14** [comment]
if this works on your machine, I'm cool with merging it

**Comment by christophercook14** [comment]
Looks good.  If Doug is cool with it, I'll merge.

**Comment by DougVonMoser** [comment]
Cool stuff

**Pull request merged**
